language: cpp
env:
  global:
    - QT5_VERSION="v5.15.0"
    - WINDOWS_QT5_INSTALL_PREFIX="/c/qt5-static"
    - LINUX_QT5_INSTALL_PREFIX="/usr/local/qt5-static"

matrix:
  include:
    # - os: linux
    #   dist: bionic
    #   compiler: gcc
    #   addons:
    #     apt:
    #       sources:
    #         - ubuntu-toolchain-r-test
    #       packages:
    #         - g++-9
    #         - libxkbcommon-dev
    #         - libgl1-mesa-dev
    #   before_install:
    #     # force qt to use desired compiler version
    #     - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 100
    #     - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-9 100
    #     - gcc --version
    #     - g++ --version

    - os: windows

    # - os: osx
    #   osx_image: xcode9.4
    #   compiler: clang

before_script:
  # download Qt5 sources
  - git clone https://code.qt.io/qt/qt5.git
  - cd qt5
  # checkout desired version
  - git checkout $QT5_VERSION
  # only need qtbase submodule
  - git submodule update --init qtbase
  - cd ../
script:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then $TRAVIS_BUILD_DIR/build-unix.sh; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then $TRAVIS_BUILD_DIR/build-windows.sh; fi

before_deploy:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then tar -zcvf qt5-static-$TRAVIS_OS_NAME.tgz $LINUX_QT5_INSTALL_PREFIX; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then 7z a $TRAVIS_BUILD_DIR/qt5-static-windows.zip $WINDOWS_QT5_INSTALL_PREFIX; fi
  - git config --local user.name "$GIT_USER_NAME"
  - git config --local user.email "$GIT_USER_EMAIL"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG

deploy:
  # if commit was tagged, upload resulting tarball to github release
  provider: releases
  api_key:
    secure: "$GITHUB_TOKEN"
  file:
    - qt5-static-$TRAVIS_OS_NAME.tgz
  skip_cleanup: true
  on:
    repo: varunamachi/qt-static-full
    # tags: true
    # all_branches: true
notifications:
  email: false
